version: '3'
services:
  web:
    image: node:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app
    command: npm start
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=MUSICS
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

